/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bolnicaController.BolnicaController;
import bolnicaController.BolnicaFormController;
import com.sun.org.apache.bcel.internal.generic.AASTORE;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Bolnica;
import model.Doktor;
import model.TipDoktora;
import model.VrstaBolnice;
import model.Zvanje;
import models.DoktoriBolnicaTableModel;
import tipDoktoraController.TipDoktoraController;
import vrstaBolniceController.VrstaBolniceController;
import zvanjeController.ZvanjeController;

/**
 *
 * @author Marenda
 */
public class KreirajBolnicu extends javax.swing.JFrame {
    private BolnicaController kontroler;
    /**
     * Creates new form KreirajBolnicu
     */
    public KreirajBolnicu() {
        initComponents();
        kontroler = new BolnicaController();
        initForma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldMaticniBroj = new javax.swing.JTextField();
        jTextFieldPoreskiBroj = new javax.swing.JTextField();
        jTextFieldOpis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPretraga = new javax.swing.JTextField();
        jComboBoxVrstaBolnice = new javax.swing.JComboBox<Object>();
        jButtonSacuvaj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldImeDoktora = new javax.swing.JTextField();
        jTextFieldPrezimeDoktora = new javax.swing.JTextField();
        jComboBoxTipDoktora = new javax.swing.JComboBox<Object>();
        jComboBoxZvanjeDoktora = new javax.swing.JComboBox<Object>();
        jButtonSacuvajDoktora = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDoktori = new javax.swing.JTable();
        jButtonObrisiDoktora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID:");

        jLabel2.setText("Naziv :");

        jLabel3.setText("Maticni broj :");

        jLabel4.setText("Poreski broj:");

        jLabel5.setText("Opis :");

        jLabel6.setText("Vrsta bolnice:");

        jLabel7.setText("Pretraga:");

        jLabel8.setText("Vrsta bolnice:");

        jTextFieldPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPretragaKeyReleased(evt);
            }
        });

        jComboBoxVrstaBolnice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jTextFieldMaticniBroj)
                            .addComponent(jTextFieldPoreskiBroj)
                            .addComponent(jTextFieldOpis)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPretraga)
                            .addComponent(jComboBoxVrstaBolnice, 0, 479, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPoreskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxVrstaBolnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSacuvaj)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Podaci o bolnici", jPanel1);

        jLabel9.setText("Ime :");

        jLabel10.setText("Prezime :");

        jLabel11.setText("Tip doktora:");

        jLabel12.setText("Zvanje :");

        jComboBoxTipDoktora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxZvanjeDoktora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSacuvajDoktora.setText("Dodaj");
        jButtonSacuvajDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajDoktoraActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jTableDoktori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDoktori);

        jButtonObrisiDoktora.setText("Obrisi");
        jButtonObrisiDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiDoktoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonObrisiDoktora, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldImeDoktora)
                            .addComponent(jTextFieldPrezimeDoktora)
                            .addComponent(jComboBoxTipDoktora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxZvanjeDoktora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonSacuvajDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldImeDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPrezimeDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxTipDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxZvanjeDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonSacuvajDoktora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonObrisiDoktora))
                .addGap(189, 189, 189))
        );

        jTabbedPane1.addTab("Doktori", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajDoktoraActionPerformed
        sacuvajDoktora();
    }//GEN-LAST:event_jButtonSacuvajDoktoraActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        odustani();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonObrisiDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiDoktoraActionPerformed
        obrisiDoktora();
    }//GEN-LAST:event_jButtonObrisiDoktoraActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        sacuvajBolnicu();
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jTextFieldPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPretragaKeyReleased
        pretraziVrsteBolnica();
    }//GEN-LAST:event_jTextFieldPretragaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisiDoktora;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonSacuvajDoktora;
    private javax.swing.JComboBox<Object> jComboBoxTipDoktora;
    private javax.swing.JComboBox<Object> jComboBoxVrstaBolnice;
    private javax.swing.JComboBox<Object> jComboBoxZvanjeDoktora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDoktori;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldImeDoktora;
    private javax.swing.JTextField jTextFieldMaticniBroj;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldOpis;
    private javax.swing.JTextField jTextFieldPoreskiBroj;
    private javax.swing.JTextField jTextFieldPretraga;
    private javax.swing.JTextField jTextFieldPrezimeDoktora;
    // End of variables declaration//GEN-END:variables

    private void initForma() {
        jTableDoktori.setModel(new DoktoriBolnicaTableModel());
        jTextFieldID.setEnabled(false);
        
        try {
            List<VrstaBolnice> vrsteBolnice = new VrstaBolniceController().loadAll();
            
            List<TipDoktora> tipoviDoktora = new TipDoktoraController().loadAll();
            List<Zvanje> zvanja = new ZvanjeController().loadAll();
            
            popuniComboBoxVrsteBolnice(vrsteBolnice);
            popuniComboBoxTipoviDoktora(tipoviDoktora);
            popuniComboBoxZvanja(zvanja);
            
            kontroler.setVrsteBolniceIzBaze(vrsteBolnice);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da popuni podatke");
            ex.printStackTrace();
        }
    }

    private void popuniComboBoxVrsteBolnice(List<VrstaBolnice> vrsteBolnice) {
        jComboBoxVrstaBolnice.removeAllItems();
        
        for (VrstaBolnice vrsteBolnice1 : vrsteBolnice) {
            jComboBoxVrstaBolnice.addItem(vrsteBolnice1);
        }
    }

    private void popuniComboBoxTipoviDoktora(List<TipDoktora> tipoviDoktora) {
        jComboBoxTipDoktora.removeAllItems();
        for (TipDoktora tipoviDoktora1 : tipoviDoktora) {
            jComboBoxTipDoktora.addItem(tipoviDoktora1);
        }
    }

    private void popuniComboBoxZvanja(List<Zvanje> zvanja) {
        jComboBoxZvanjeDoktora.removeAllItems();
        
        for (Zvanje zvanja1 : zvanja) {
            jComboBoxZvanjeDoktora.addItem(zvanja1);
        }
    }

    private void sacuvajDoktora() {
        try{
            String ime = jTextFieldImeDoktora.getText().trim();
            String prezime = jTextFieldPrezimeDoktora.getText().trim();
            TipDoktora tipDoktora = (TipDoktora) jComboBoxTipDoktora.getSelectedItem();
            Zvanje zvanje = (Zvanje) jComboBoxZvanjeDoktora.getSelectedItem();
            
            Doktor doktor = new Doktor(ime, prezime);
            doktor.setTipDoktora(tipDoktora);
            doktor.setZvanje(zvanje);
            
            getDoktoriBolnicaTableModel().dodajDoktora(doktor);
            
            resetujPoljaZaDoktora();
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private DoktoriBolnicaTableModel getDoktoriBolnicaTableModel(){
        return (DoktoriBolnicaTableModel) jTableDoktori.getModel();
    }

    private void resetujPoljaZaDoktora() {
        jTextFieldImeDoktora.setText("");
        jTextFieldPrezimeDoktora.setText("");
        jComboBoxTipDoktora.setSelectedIndex(0);
        jComboBoxZvanjeDoktora.setSelectedIndex(0);
    }

    private void odustani() {
        resetujPoljaZaDoktora();
        
    }

    private void obrisiDoktora() {
        int selectedIndex = jTableDoktori.getSelectedRow();
        
        if(selectedIndex >= 0){
            getDoktoriBolnicaTableModel().obrisi(selectedIndex);
        }else{
            JOptionPane.showMessageDialog(this, "Morate izabrani doktora da biste ga obrisali");
        }
    }

    private void sacuvajBolnicu() {
        try{
            String id = jTextFieldID.getText().trim();
            
            if(!id.isEmpty()){
                throw new Exception("Bolnica sa id-em" + id + " je vec kreirana");
            }
            
            String naziv = jTextFieldNaziv.getText().trim();
            String maticniBroj = jTextFieldMaticniBroj.getText().trim();
            String poreskiBroj = jTextFieldPoreskiBroj.getText().trim();
            String opis = jTextFieldOpis.getText().trim();
            
            VrstaBolnice vb = (VrstaBolnice) jComboBoxVrstaBolnice.getSelectedItem();
            
            List<Doktor> doktori = getDoktoriBolnicaTableModel().getDoktori();
            
            Bolnica sacuvana = kontroler.save(naziv, maticniBroj, poreskiBroj, opis, vb, doktori);
            
            new Thread(new Runnable() {

                @Override
                public void run() {
                    BolnicaFormController.getInstance().bolnicaChanged();
                }
            }).start();
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio bolnicu");
            resetujPoljaZaBolnicu();
            initForma();
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti podatke o bolnici");
        }
    }

    private void pretraziVrsteBolnica() {
        String filter = jTextFieldPretraga.getText().trim();
        List<VrstaBolnice> filtrirane = kontroler.pronadjiVrsteBolnice(filter);
        popuniComboBoxVrsteBolnice(filtrirane);
    }

    private void resetujPoljaZaBolnicu() {
        jTextFieldMaticniBroj.setText("");
        jTextFieldNaziv.setText("");
        jTextFieldPoreskiBroj.setText("");
        jTextFieldPretraga.setText("");
        jTextFieldOpis.setText("");
    }
}
