/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import enumeration.ZvanjeState;
import model.Zvanje;
import zvanjeController.ZvanjeController;
import zvanjeController.ZvanjeFormController;

/**
 *
 * @author Marenda
 */
public class KreirajIliIzmeniZvanje extends javax.swing.JFrame {
    private ZvanjeController kontroler;
    private ZvanjeState state;
    /**
     * Creates new form KreirajIliIzmeniZvanje
     */
    public KreirajIliIzmeniZvanje() {
        initComponents();
        kontroler = new ZvanjeController();
        state = ZvanjeState.CREATE;
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jButtonAkcija = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Podaci o zvanju : ");

        jLabel2.setText("Id : ");

        jLabel3.setText("Naziv : ");

        jButtonAkcija.setText("Kreiraj");
        jButtonAkcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAkcijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAkcija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNaziv))
                            .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAkcija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAkcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAkcijaActionPerformed
        doAction();
    }//GEN-LAST:event_jButtonAkcijaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAkcija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        prepareForm();
    }

    private void prepareForm() {
        resetFields();
        enableFields();
        if(state == ZvanjeState.CREATE){
            setTitle("Kreiraj zvanje");
            jTextFieldId.setEnabled(false);
            jButtonAkcija.setText("Kreiraj");
        }else{
            setTitle("Izmeni zvanje");
            jButtonAkcija.setText("Izmeni");
        }
    }

    private void resetFields() {
        jTextFieldId.setText("");
        jTextFieldNaziv.setText("");
    }

    private void enableFields() {
        jTextFieldId.setEnabled(true);
        jTextFieldNaziv.setEnabled(true);
    }

    private void doAction() {
        String naziv = jTextFieldNaziv.getText().trim();
        try{
            if(state == ZvanjeState.CREATE){
                Zvanje kreiranoZvanje = kontroler.kreirajZvanje(naziv);
                jLabelMessage.setText("Sistem je zapamtio zvanje");
                setState(ZvanjeState.UPDATE);
                jTextFieldId.setText(kreiranoZvanje.getId() + "");
                jTextFieldNaziv.setText(kreiranoZvanje.getNaziv());
            }else{
                Integer id = Integer.parseInt(jTextFieldId.getText().trim());
                kontroler.updateZvanje(id, naziv);
                jLabelMessage.setText("Zvanje je azurirano");
            }
            ZvanjeFormController.getInstance().zvanjeChanged();
        }catch(Exception ex){
            jLabelMessage.setText("Sistem ne moze da zapamti podatke o zvanju");
        }
    }

    public void setState(ZvanjeState state) {
        this.state = state;
        prepareForm();
    }
    
    public void setValues(Zvanje z){
        jTextFieldId.setText(z.getId() + "");
        jTextFieldNaziv.setText(z.getNaziv());
    }
}
