/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bolnicaController.BolnicaController;
import doktorController.DoktorController;
import doktorController.DoktorFormController;
import enumeration.DoktorState;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Bolnica;
import model.Doktor;
import model.TipDoktora;
import model.Zvanje;
import tipDoktoraController.TipDoktoraController;

/**
 *
 * @author Marenda
 */
public class KreirajIzmeniDoktora extends javax.swing.JFrame {

    private DoktorState status;
    private DoktorController controller;

    /**
     * Creates new form KreirajIzmeniDoktora
     */
    public KreirajIzmeniDoktora() throws Exception {
        initComponents();
        controller = new DoktorController();
        status = DoktorState.KREIRAJ;
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPretragaBolnica = new javax.swing.JTextField();
        jButtonPretragaBolnica = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxBolnica = new javax.swing.JComboBox<Object>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPretragaTipaDoktora = new javax.swing.JTextField();
        jButtonPretragaTipaDoktora = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTipDoktora = new javax.swing.JComboBox<Object>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPretragaZvanja = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxZvanje = new javax.swing.JComboBox<Object>();
        jButtonAction = new javax.swing.JButton();
        jButtonPretragaZvanja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID:");

        jLabel2.setText("Podaci o doktoru");

        jLabel3.setText("Ime :");

        jLabel4.setText("Prezime");

        jLabel5.setText("Izaberite bolnicu");

        jLabel6.setText("Pretraga:");

        jTextFieldPretragaBolnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPretragaBolnicaActionPerformed(evt);
            }
        });

        jButtonPretragaBolnica.setText("Pretraga");
        jButtonPretragaBolnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaBolnicaActionPerformed(evt);
            }
        });

        jLabel7.setText("Bolnica:");

        jComboBoxBolnica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Izaberite tip doktora:");

        jLabel9.setText("Pretraga:");

        jButtonPretragaTipaDoktora.setText("Pretraga");
        jButtonPretragaTipaDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaTipaDoktoraActionPerformed(evt);
            }
        });

        jLabel10.setText("Tip doktora:");

        jComboBoxTipDoktora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Izaberite zvanje doktora:");

        jLabel12.setText("Pretraga:");

        jLabel13.setText("Zvanje:");

        jComboBoxZvanje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAction.setText("Kreiraj");
        jButtonAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionActionPerformed(evt);
            }
        });

        jButtonPretragaZvanja.setText("Pretraga");
        jButtonPretragaZvanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaZvanjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxZvanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPretragaZvanja, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPretragaZvanja, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPretragaBolnica, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPretragaBolnica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                                .addComponent(jTextFieldIme)
                                .addComponent(jTextFieldId)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                                .addComponent(jTextFieldPrezime))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxBolnica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPretragaTipaDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPretragaTipaDoktora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTipDoktora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPretragaBolnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretragaBolnica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxBolnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPretragaTipaDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretragaTipaDoktora))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxTipDoktora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldPretragaZvanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretragaZvanja))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonAction)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionActionPerformed
        if (status == DoktorState.KREIRAJ) {
            save();
        } else {
            updateDoktora();
        }
    }//GEN-LAST:event_jButtonActionActionPerformed

    private void jTextFieldPretragaBolnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPretragaBolnicaActionPerformed

    }//GEN-LAST:event_jTextFieldPretragaBolnicaActionPerformed

    private void jButtonPretragaBolnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaBolnicaActionPerformed
        pronadjiBolnice();
    }//GEN-LAST:event_jButtonPretragaBolnicaActionPerformed

    private void jButtonPretragaTipaDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaTipaDoktoraActionPerformed
        pronadjiTipoveDoktora();
    }//GEN-LAST:event_jButtonPretragaTipaDoktoraActionPerformed

    private void jButtonPretragaZvanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaZvanjaActionPerformed
        pronadjiZvanja();
    }//GEN-LAST:event_jButtonPretragaZvanjaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAction;
    private javax.swing.JButton jButtonPretragaBolnica;
    private javax.swing.JButton jButtonPretragaTipaDoktora;
    private javax.swing.JButton jButtonPretragaZvanja;
    private javax.swing.JComboBox<Object> jComboBoxBolnica;
    private javax.swing.JComboBox<Object> jComboBoxTipDoktora;
    private javax.swing.JComboBox<Object> jComboBoxZvanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPretragaBolnica;
    private javax.swing.JTextField jTextFieldPretragaTipaDoktora;
    private javax.swing.JTextField jTextFieldPretragaZvanja;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void initForm() throws Exception {
        jTextFieldId.setEnabled(false);
        try {
            List<Zvanje> zvanja = new zvanjeController.ZvanjeController().loadAll();
            List<TipDoktora> tipoviDoktora = new TipDoktoraController().loadAll();
            List<Bolnica> bolnice = new BolnicaController().loadAll();

            controller.setBolniceIzBaze(bolnice);
            controller.setTipoviDoktoraIzBaze(tipoviDoktora);
            controller.setZvanjaIzBaze(zvanja);

            populateComboBoxZvanja(zvanja);
            populateComboBoxTipoviDoktora(tipoviDoktora);
            populateComboBoxBolnice(bolnice);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void populateComboBoxZvanja(List<Zvanje> zvanja) {
        jComboBoxZvanje.removeAllItems();

        for (Zvanje zvanja1 : zvanja) {
            jComboBoxZvanje.addItem(zvanja1);
        }
    }

    private void populateComboBoxTipoviDoktora(List<TipDoktora> tipoviDoktora) {
        jComboBoxTipDoktora.removeAllItems();

        for (TipDoktora tipoviDoktora1 : tipoviDoktora) {
            jComboBoxTipDoktora.addItem(tipoviDoktora1);
        }
    }

    private void populateComboBoxBolnice(List<Bolnica> bolnice) {
        jComboBoxBolnica.removeAllItems();

        for (Bolnica bolnice1 : bolnice) {
            jComboBoxBolnica.addItem(bolnice1);
        }
    }

    private void save() {
        try {
            String id = jTextFieldId.getText().trim();
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();

            Bolnica bolnica = (Bolnica) jComboBoxBolnica.getSelectedItem();
            TipDoktora tipDoktora = (TipDoktora) jComboBoxTipDoktora.getSelectedItem();
            Zvanje zvanje = (Zvanje) jComboBoxZvanje.getSelectedItem();

            Doktor kreirani = controller.create(ime, prezime, bolnica, tipDoktora, zvanje);
            DoktorFormController.getInstance().doktorChanged();
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio doktora");

            resetFields();
            populateFields(kreirani);

            setState(DoktorState.IZMENI);
            populateFields(kreirani);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti podatke o doktoru");
        }
    }

    private void updateDoktora() {
        try {
            Integer ID = Integer.parseInt(jTextFieldId.getText().trim());
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            Bolnica bolnica = (Bolnica) jComboBoxBolnica.getSelectedItem();
            TipDoktora tipDoktora = (TipDoktora) jComboBoxTipDoktora.getSelectedItem();
            Zvanje zvanje = (Zvanje) jComboBoxZvanje.getSelectedItem();

            controller.update(ID, ime, prezime, bolnica, tipDoktora, zvanje);
            System.out.println("ID : " + ID);
            DoktorFormController.getInstance().doktorChanged();
            JOptionPane.showMessageDialog(this, "Podaci o doktoru uspesno promenjeni");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne moze da azurira doktora");
        }
    }

    private void resetFields() {
        jTextFieldId.setText("");
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jComboBoxBolnica.setSelectedIndex(0);
        jComboBoxTipDoktora.setSelectedIndex(0);
        jComboBoxZvanje.setSelectedIndex(0);

        jTextFieldPretragaBolnica.setText("");
        jTextFieldPretragaTipaDoktora.setText("");
        jTextFieldPretragaZvanja.setText("");

    }

    private void populateFields(Doktor d) {
        jTextFieldId.setText(d.getId() + "");
        jTextFieldIme.setText(d.getIme());
        jTextFieldPrezime.setText(d.getPrezime());
        jComboBoxBolnica.setSelectedItem(d.getBolnica());
        jComboBoxTipDoktora.setSelectedItem(d.getTipDoktora());
        jComboBoxZvanje.setSelectedItem(d.getZvanje());
    }

    public void setState(DoktorState state) {
        this.status = state;
        pripremiFormu();
    }

    private void pripremiFormu() {
        resetFields();
        if (status == DoktorState.KREIRAJ) {
            jButtonAction.setText("SACUVAJ");
            setTitle("CREATE");
        } else if (status == DoktorState.IZMENI) {
            jButtonAction.setText("IZMENI");
            setTitle("UPDATE");
        }
    }

    public void setValues(Integer id) throws Exception {
        Doktor d = controller.loadById(id);
        populateFields(d);
    }

    private void pronadjiBolnice() {
        String filter = jTextFieldPretragaBolnica.getText().trim();
        List<Bolnica> bolnice = controller.pronadjiBolnice(filter);
        populateComboBoxBolnice(bolnice);
    }

    private void pronadjiZvanja() {
        String filter = jTextFieldPretragaZvanja.getText().trim();
        List<Zvanje> zvanja = controller.pronadjIZvanja(filter);
        populateComboBoxZvanja(zvanja);
    }

    private void pronadjiTipoveDoktora() {
        String filter = jTextFieldPretragaTipaDoktora.getText().trim();
        List<TipDoktora> tipoviDoktora = controller.pronadjiTipoveDoktora(filter);
        populateComboBoxTipoviDoktora(tipoviDoktora);
    }
    
}
