/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bolnicaController.BolnicaController;
import bolnicaController.BolnicaFormController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Bolnica;
import models.BolnicaTableModel;

/**
 *
 * @author Marenda
 */
public class PrikazSvihBolnica extends javax.swing.JFrame {
    private BolnicaController kontroler;
    /**
     * Creates new form PrikazSvihBolnica
     */
    public PrikazSvihBolnica() {
        initComponents();
        kontroler = new BolnicaController();
        initForma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBolnice = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonKreirajBolnicu = new javax.swing.JButton();
        jButtonPrikaziBolnicu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableBolnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableBolnice);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prikaz svih bolnica : ");

        jButtonKreirajBolnicu.setText("Kreiraj");
        jButtonKreirajBolnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajBolnicuActionPerformed(evt);
            }
        });

        jButtonPrikaziBolnicu.setText("Prikazi");
        jButtonPrikaziBolnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziBolnicuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKreirajBolnicu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrikaziBolnicu, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonKreirajBolnicu)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonPrikaziBolnicu)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajBolnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajBolnicuActionPerformed
        prikaziFormuZaKreiranjeBolnice();
    }//GEN-LAST:event_jButtonKreirajBolnicuActionPerformed

    private void jButtonPrikaziBolnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziBolnicuActionPerformed
        prikaziIzabranuBolnicu();
    }//GEN-LAST:event_jButtonPrikaziBolnicuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreirajBolnicu;
    private javax.swing.JButton jButtonPrikaziBolnicu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBolnice;
    // End of variables declaration//GEN-END:variables

    public void initForma() {
        try{
            List<Bolnica> bolnice = kontroler.loadAll();
            jTableBolnice.setModel(new BolnicaTableModel(bolnice));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void prikaziFormuZaKreiranjeBolnice() {
        BolnicaFormController.getInstance().prikaziFormuZaKreiranjeBolnica();
    }

    private void prikaziIzabranuBolnicu() {
        int selectedIndex = jTableBolnice.getSelectedRow();
        
        if(selectedIndex >= 0){
            try{
                Bolnica bolnica = getModel().getSelectedBolnica(selectedIndex);
                BolnicaFormController.getInstance().prikaziIzabranuBolnicu(bolnica.getId());
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Izaberite bolnicu");
        }
    }
    
    private BolnicaTableModel getModel(){
        return (BolnicaTableModel) jTableBolnice.getModel();
    }

   

    
}
