/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bolnicaController.BolnicaController;
import bolnicaController.BolnicaFormController;
import doktorController.DoktorController;
import doktorController.DoktorFormController;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Bolnica;
import model.Doktor;
import models.DoktoriTableModel;

/**
 *
 * @author Marenda
 */
public class PrikazIzabraneBolnice extends javax.swing.JFrame {

    private BolnicaController kontroler;
    private Integer bolnicaID;

    /**
     * Creates new form PrikazIzabraneBolnice
     */
    public PrikazIzabraneBolnice() {
        initComponents();
        kontroler = new BolnicaController();
        initForma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNazivBolnice = new javax.swing.JTextField();
        jTextFieldMaticniBroj = new javax.swing.JTextField();
        jTextFieldPoreskiBroj = new javax.swing.JTextField();
        jTextFieldOpis = new javax.swing.JTextField();
        jTextFieldVrstaBolnice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDoktori = new javax.swing.JTable();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonKreirajDoktora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Naziv");

        jLabel3.setText("Maticni broj");

        jLabel4.setText("Poreski broj");

        jLabel5.setText("Opis");

        jLabel6.setText("Vrsta bolnice");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldID)
                    .addComponent(jTextFieldNazivBolnice)
                    .addComponent(jTextFieldMaticniBroj)
                    .addComponent(jTextFieldPoreskiBroj)
                    .addComponent(jTextFieldOpis)
                    .addComponent(jTextFieldVrstaBolnice, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNazivBolnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPoreskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldVrstaBolnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Podaci o bolnici", jPanel1);

        jTableDoktori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDoktori);

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonKreirajDoktora.setText("Kreiraj doktora");
        jButtonKreirajDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajDoktoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKreirajDoktora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonIzmeni)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonObrisi)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonKreirajDoktora))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Doktori", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        prikaziFormuZaIzmenuDoktora();
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        obrisiDoktora();
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonKreirajDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajDoktoraActionPerformed
        prikaziFormuZaKreiranjeDoktora();
    }//GEN-LAST:event_jButtonKreirajDoktoraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreirajDoktora;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDoktori;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldMaticniBroj;
    private javax.swing.JTextField jTextFieldNazivBolnice;
    private javax.swing.JTextField jTextFieldOpis;
    private javax.swing.JTextField jTextFieldPoreskiBroj;
    private javax.swing.JTextField jTextFieldVrstaBolnice;
    // End of variables declaration//GEN-END:variables

    private void initForma() {
        jTableDoktori.setModel(new DoktoriTableModel(new ArrayList<>()));
    }

    private void prikaziFormuZaIzmenuDoktora() {
        try {
            int id = getModel().getDoktor(jTableDoktori.getSelectedRow()).getId();
            DoktorFormController.getInstance().openUpdateDoctorForm(id);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private DoktoriTableModel getModel() {
        return (DoktoriTableModel) jTableDoktori.getModel();
    }

    private void obrisiDoktora() {
        try {
            int selectedIndex = jTableDoktori.getSelectedRow();
            Doktor zaBrisanje = getModel().getDoktor(selectedIndex);
            new DoktorController().delete(zaBrisanje);
            JOptionPane.showMessageDialog(this, "Doktor : " + zaBrisanje.getIme() + " " + zaBrisanje.getPrezime() + " je uspesno obrisan");
            setId(bolnicaID);
        } catch (Exception ex) {

        }
    }

    public void setId(Integer id) throws Exception {
        Bolnica b = kontroler.loadById(id);
        bolnicaID = id;
        setBolnica(b);
    }

    private void setBolnica(Bolnica bolnica) {
        popuniPolja(bolnica);
        popuniTabelu(bolnica.getDoktori());
    }

    private void popuniPolja(Bolnica bolnica) {
        jTextFieldID.setText(bolnica.getId() + "");
        jTextFieldNazivBolnice.setText(bolnica.getNaziv());
        jTextFieldMaticniBroj.setText(bolnica.getMaticniBroj());
        jTextFieldPoreskiBroj.setText(bolnica.getPoreskiBroj());
        jTextFieldOpis.setText(bolnica.getOpis());
        jTextFieldVrstaBolnice.setText(bolnica.getVrstaBolnice().getNaziv());
    }

    private void popuniTabelu(List<Doktor> doktori) {
        jTableDoktori.setModel(new DoktoriTableModel(doktori));
    }

    private void prikaziFormuZaKreiranjeDoktora() {
        try {
            DoktorFormController.getInstance().openCreateDoctorForm();
            BolnicaFormController.getInstance().izabranaBolnicaChanged();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void osvezi() {
        try {
            popuniTabeluDoktori();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void popuniTabeluDoktori() throws Exception {

        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    Bolnica b = new BolnicaController().loadById(Integer.parseInt(jTextFieldID.getText().trim()));
                    popuniTabelu(b.getDoktori());
                } catch (Exception ex) {
                    ex.printStackTrace();
//                        JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        });
        thread.start();
    }

}
